### ISSUE TITLE
Uncaught Error: Flynt\Utils\acf_add_options_page()

### ISSUE THREAD

**Issue by KristofKreimeyer** [flyntwp/flynt#234]
Hi guys,

i installed Flynt, changed the const host to localhost and called https:localhost:3000. 
Then i installed the plugin that you have to install and after reloading the page i got this error. 

Maybe someone could get me a hint what to do now ;-)

Fatal error: Uncaught Error: Call to undefined function Flynt\Utils\acf_add_options_page() in C:\xampp\htdocs\wp-content\themes\flynt\lib\Utils\Options.php:77 Stack trace: #0 C:\xampp\htdocs\wp-content\themes\flynt\lib\Utils\Options.php(96): Flynt\Utils\Options::createOptionPage('global') #1 C:\xampp\htdocs\wp-content\themes\flynt\lib\Utils\Options.php(204): Flynt\Utils\Options::createOptionSubPage('global', 'Default') #2 C:\xampp\htdocs\wp-content\themes\flynt\lib\Utils\Options.php(199): Flynt\Utils\Options::addOptions('Acf', Array, 'global', 'Default') #3 C:\xampp\htdocs\wp-content\themes\flynt\inc\acf.php(33): Flynt\Utils\Options::addGlobal('Acf', Array) #4 C:\xampp\htdocs\wp-content\themes\flynt\lib\Utils\FileLoader.php(66): require_once('C:\\xampp\\htdocs...') #5 [internal function]: Flynt\Utils\FileLoader::Flynt\Utils\{closure}(Object(DirectoryIterator)) #6 C:\xampp\htdocs\wp-content\themes\flynt\lib\Utils\FileLoader.php(34): call_user_func(Object(Closure), Object(DirectoryIterator)) #7 C:\xampp\htdocs\wp-content\th in C:\xampp\htdocs\wp-content\themes\flynt\lib\Utils\Options.php on line 77

**Comment by domtra** [comment]
Hi @KristofKreimeyer ,
it seems that you do not have Advanced Custom Fields Pro active. It cannot find the function `acf_add_options_page()`. Unfortunately, this function is not part of the free ACF plugin, but only of the paid Pro version.
We are currently looking into providing a similar experience with a free plugin but do not have a solution for that, yet. 
Hope I could help you out.

**Comment by domtra** [comment]
closing this due to inactivity. @KristofKreimeyer let me know if we can support you in any other way.
