### ISSUE TITLE
Activating Yoast SEO creates fatal error

### ISSUE THREAD

**Issue by spencermerpi** [flyntwp/flynt#239]
When I activate the Yoast SEO plugin, I get this fatal error: 

`Fatal error: Uncaught Error: Class 'Flynt\Init' not found in /Users/spencer/DEKSIA/flynt/wp-content/themes/flynt/functions.php:16 Stack trace: #0 /Users/spencer/DEKSIA/flynt/wp-settings.php(497): include() #1 /Users/spencer/DEKSIA/flynt/wp-config.php(90): require_once('/Users/spencer/...') #2 /Users/spencer/DEKSIA/flynt/wp-load.php(37): require_once('/Users/spencer/...') #3 /Users/spencer/DEKSIA/flynt/wp-admin/admin.php(34): require_once('/Users/spencer/...') #4 /Users/spencer/DEKSIA/flynt/wp-admin/plugins.php(10): require_once('/Users/spencer/...') #5 {main} thrown in /Users/spencer/DEKSIA/flynt/wp-content/themes/flynt/functions.php on line 16`

**Comment by spencermerpi** [comment]
I found out my composer was out of date. When I updated composer, this issue was resolved
