### ISSUE TITLE
Attempted PHP update broke WordPress Website

### ISSUE THREAD

**Issue by isaacbraun** [flyntwp/flynt#281]
I'm running Flynt with the latest WordPress release on an AWS Lightsail Instance. WordPress dashboard suggested that my PHP version should be updated to 7.4, and so I tried to update my server's PHP version to 7.4 through the command line. I must have done something wrong, since the command "php -v" still shows an older version and my server homepage shows the default Apache2 page, not WordPress. I'm at a loss here and wondered if this is a conflicting issue within Flynt or if I just did something completely wrong that broke WordPress. Any help would be greatly appreciated. Thanks.

**Comment by isaacbraun** [comment]
This is the error that `npm run start` is throwing

` error  in ./assets/admin.js`

`Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'`
`Require stack:`
`- /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/flynt/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js`
`- /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/flynt/node_modules/@babel/preset-env/lib/index.js`
`- /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/flynt/node_modules/@babel/core/lib/config/files/plugins.js`
`- /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/flynt/node_modules/@babel/core/lib/config/files/index.js`
`- /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/flynt/node_modules/@babel/core/lib/index.js`
`- /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/flynt/node_modules/babel-loader/lib/index.js`
`- /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/flynt/node_modules/loader-runner/lib/loadLoader.js`
`- /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/flynt/node_modules/loader-runner/lib/LoaderRunner.js`
`- /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/flynt/node_modules/webpack/lib/NormalModule.js`
`- /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/flynt/node_modules/webpack/lib/NormalModuleFactory.js`
`- /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/flynt/node_modules/webpack/lib/Compiler.js`
`- /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/flynt/node_modules/webpack/lib/webpack.js`
`- /opt/bitnami/apps/wordpress/htdocs/wp-content/themes/flynt/bs-server.js`
`    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)`
`    at Function.Module._load (internal/modules/cjs/loader.js:842:27)`
`    at Module.require (internal/modules/cjs/loader.js:1026:19)`
`    at require (internal/modules/cjs/helpers.js:72:18)`
`    at Object.<anonymous> (/opt/bitnami/apps/wordpress/htdocs/wp-content/themes/flynt/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)`
`    at Module._compile (internal/modules/cjs/loader.js:1138:30)`
`    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)`
`    at Module.load (internal/modules/cjs/loader.js:986:32)`
`    at Function.Module._load (internal/modules/cjs/loader.js:879:14)`
`    at Module.require (internal/modules/cjs/loader.js:1026:19)`
`    at require (internal/modules/cjs/helpers.js:72:18)`
`    at Object.<anonymous> (/opt/bitnami/apps/wordpress/htdocs/wp-content/themes/flynt/node_modules/@babel/preset-env/lib/index.js:29:44)`
`    at Module._compile (internal/modules/cjs/loader.js:1138:30)`
`    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)`
`    at Module.load (internal/modules/cjs/loader.js:986:32)`
`    at Function.Module._load (internal/modules/cjs/loader.js:879:14)`

**Comment by isaacbraun** [comment]
I am no longer attempting to fix this.
